export const QUESTIONS = [
  {
    id: 1,
    question: "Am the life of the party.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "c",
  },
  {
    id: 2,
    question: "Feel little concern for others",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 3,
    question: "Am always prepared.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 4,
    question: "Get stressed out easily.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 5,
    question: "Have a rich vocabulary.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 6,
    question: "Don't talk a lot.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 7,
    question: "Am interested in people",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 8,
    question: "Leave my belongings around.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 9,
    question: "Am relaxed most of the time.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 10,
    question: "Have difficulty understanding abstract ideas.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 11,
    question: "Feel comfortable around people.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 12,
    question: "Insult people.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 13,
    question: "Pay attention to details.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 14,
    question: "Worry about things.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 15,
    question: "Have a vivid imagination.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 16,
    question: "Keep in the background.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 17,
    question: "Sympathize with others' feelings.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 18,
    question: "Make a mess of things.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 19,
    question: "Seldom feel blue.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 20,
    question: "Am not interested in abstract ideas.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 21,
    question: "Start conversations.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 22,
    question: "Am not interested in other people's problems.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 23,
    question: "Get chores done right away.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 24,
    question: "Am easily disturbed.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 25,
    question: "Have excellent ideas.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 26,
    question: "Have little to say.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 27,
    question: "Have a soft heart",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 28,
    question: "Often forget to put things back in their proper place.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 29,
    question: "Get upset easily.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 30,
    question: "Do not have a good imagination.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 31,
    question: "Talk to a lot of different people at parties.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 32,
    question: "Am not really interested in others.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 33,
    question: "Like order.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 34,
    question: "Change my mood a lot.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 35,
    question: "Am quick to understand things.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 36,
    question: "Don't like to draw attention to myself.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 37,
    question: "Take time out for others.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 38,
    question: "Shirk my duties",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 39,
    question: "Have frequent mood swings.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 40,
    question: "Use difficult words.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 41,
    question: "Don't mind being the center of attention",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 42,
    question: "Feel others' emotions.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 43,
    question: "Follow a schedule.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 44,
    question: "Get irritated easily.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 45,
    question: "Spend time reflecting on things.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 46,
    question: "Am quiet around strangers.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 47,
    question: "Make people feel at ease.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 48,
    question: "Am exacting in my work.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 49,
    question: "Often feel blue.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
  {
    id: 50,
    question: "Am full of ideas.",
    "very less": "1",
    less: "2",
    ok: "3",
    more: "4",
    "very more": "5",
    answer: "b",
  },
];
